# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad80b331be6efb2f168b7dab30ae7b1291abbf9501effeb529a77d4764c6189876c65b790fbfe2a0b5dd24508556fab482a1e214bce7258de45b5d60665971fe

test:
  secret_key_base: 2697d607e677845d313bc27f20e72a1a09fd665347d5094ac28baacc34159d9d61c169402c0f9243d1991f89bb9b6c7e1295d11947c6c0b56b06db6b0fa3a274

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
